language: android

android:
  components:
    - build-tools-23.0.3
    - android-23
    - addon-google_apis-google-21
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-addon-google_apis-google-21

before_install:
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:21" --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - ./scripts/wait_for_emulator.sh
  - adb shell input keyevent 82 &